param([Parameter(Mandatory=$true)][string]$SourceRoot)
$ErrorActionPreference = 'Stop'
$path = Join-Path $SourceRoot 'src\PdfRescue.App\MainWindow.xaml'
$text = [IO.File]::ReadAllText($path).Replace("`r`n", "`n")
function Replace-One([string]$old,[string]$new,[string]$label) {
    if (-not $script:text.Contains($old)) { throw "Accessibility target not found: $label" }
    $script:text = $script:text.Replace($old,$new)
}

Replace-One '<TextBox x:Name="HomeSearchBox" Grid.Column="1" Background="Transparent" BorderThickness="0" Padding="0"' '<TextBox x:Name="HomeSearchBox" Grid.Column="1" Background="Transparent" BorderThickness="0" Padding="0" AutomationProperties.Name="Search recent PDF files" AutomationProperties.HelpText="Search the recent-files list. Shortcut Ctrl+K."' 'home search'
Replace-One '<Button Style="{StaticResource FlatButtonStyle}" Width="42" Margin="0" ToolTip="About, diagnostics and updates" Click="About_Click">' '<Button Style="{StaticResource FlatButtonStyle}" Width="42" Margin="0" ToolTip="About, diagnostics and updates" Click="About_Click" AutomationProperties.Name="About, diagnostics and updates">' 'about button'
Replace-One '<Button x:Name="ThemeToggleButton" Style="{StaticResource FlatButtonStyle}" Width="42" Margin="0" Click="ThemeToggle_Click" ToolTip="Switch theme">' '<Button x:Name="ThemeToggleButton" Style="{StaticResource FlatButtonStyle}" Width="42" Margin="0" Click="ThemeToggle_Click" ToolTip="Switch theme" AutomationProperties.Name="Switch light or dark theme" AutomationProperties.HelpText="Immediately toggles between light and dark appearance.">' 'theme toggle'
Replace-One '<Button x:Name="SettingsButton" Style="{StaticResource FlatButtonStyle}" Width="42" Margin="0" ToolTip="Settings" Click="Settings_Click">' '<Button x:Name="SettingsButton" Style="{StaticResource FlatButtonStyle}" Width="42" Margin="0" ToolTip="Settings" Click="Settings_Click" AutomationProperties.Name="Settings">' 'settings button'
Replace-One '<Button Style="{StaticResource FlatButtonStyle}" Width="46" Margin="0" Click="MinimizeWindow_Click" ToolTip="Minimize">' '<Button Style="{StaticResource FlatButtonStyle}" Width="46" Margin="0" Click="MinimizeWindow_Click" ToolTip="Minimize" AutomationProperties.Name="Minimize AsantePDF window">' 'minimize button'
Replace-One '<Button Style="{StaticResource FlatButtonStyle}" Width="46" Margin="0" Click="MaximizeWindow_Click" ToolTip="Maximize">' '<Button Style="{StaticResource FlatButtonStyle}" Width="46" Margin="0" Click="MaximizeWindow_Click" ToolTip="Maximize" AutomationProperties.Name="Maximize or restore AsantePDF window">' 'maximize button'
Replace-One '<Button Style="{StaticResource FlatButtonStyle}" Width="46" Margin="0" Click="CloseWindow_Click" ToolTip="Close">' '<Button Style="{StaticResource FlatButtonStyle}" Width="46" Margin="0" Click="CloseWindow_Click" ToolTip="Close" AutomationProperties.Name="Close AsantePDF window">' 'close button'
Replace-One '<ListBox x:Name="DocumentTabsList" Grid.Column="0" SelectionMode="Single"' '<ListBox x:Name="DocumentTabsList" Grid.Column="0" SelectionMode="Single" AutomationProperties.Name="Open PDF document tabs" AutomationProperties.HelpText="Select a PDF tab. Ctrl+Tab changes tabs and Ctrl+W closes the active tab."' 'document tabs'
Replace-One 'ToolTip="Close tab (Ctrl+W)" />' 'ToolTip="Close tab (Ctrl+W)" AutomationProperties.Name="Close this PDF tab" />' 'tab close'
Replace-One '<Button x:Name="CompareTabsButton" Style="{StaticResource FlatButtonStyle}" Width="42" Margin="2,3" Click="OpenSplitView_Click" IsEnabled="False" ToolTip="Compare two open PDFs side by side">' '<Button x:Name="CompareTabsButton" Style="{StaticResource FlatButtonStyle}" Width="42" Margin="2,3" Click="OpenSplitView_Click" IsEnabled="False" ToolTip="Compare two open PDFs side by side" AutomationProperties.Name="Compare two open PDFs side by side">' 'compare button'
Replace-One '<Button Style="{StaticResource FlatButtonStyle}" Width="42" Margin="2,3" Click="OpenPdf_Click" ToolTip="Open another PDF">' '<Button Style="{StaticResource FlatButtonStyle}" Width="42" Margin="2,3" Click="OpenPdf_Click" ToolTip="Open another PDF" AutomationProperties.Name="Open another PDF">' 'open another PDF'
Replace-One '<TextBox x:Name="PageNumberBox" Width="48" Height="30" TextAlignment="Center" IsEnabled="{Binding IsEnabled, ElementName=SaveButton}" KeyDown="PageNumberBox_KeyDown" Margin="7,0,4,0" />' '<TextBox x:Name="PageNumberBox" Width="48" Height="30" TextAlignment="Center" IsEnabled="{Binding IsEnabled, ElementName=SaveButton}" KeyDown="PageNumberBox_KeyDown" Margin="7,0,4,0" AutomationProperties.Name="Current page number" AutomationProperties.HelpText="Enter a page number and press Enter to jump to that page." />' 'page number'
Replace-One '<Button x:Name="ZoomButton" Style="{StaticResource FlatButtonStyle}" Click="ActualSizeShell_Click" IsEnabled="{Binding IsEnabled, ElementName=SaveButton}" Content="100%" MinWidth="66" Padding="7,4" />' '<Button x:Name="ZoomButton" Style="{StaticResource FlatButtonStyle}" Click="ActualSizeShell_Click" IsEnabled="{Binding IsEnabled, ElementName=SaveButton}" Content="100%" MinWidth="66" Padding="7,4" AutomationProperties.Name="Zoom percentage and actual size" AutomationProperties.HelpText="Shows current zoom. Activate to return to 100 percent." />' 'zoom button'
Replace-One '<ComboBox x:Name="PageViewModeCombo" Width="128" Height="30" Margin="12,0,0,0"' '<ComboBox x:Name="PageViewModeCombo" Width="128" Height="30" Margin="12,0,0,0" AutomationProperties.Name="PDF viewing mode" AutomationProperties.HelpText="Choose Single Page, Continuous, or Two Page view."' 'page view selector'
Replace-One '<TextBox x:Name="DocumentSearchBox" Width="205" Height="29" VerticalContentAlignment="Center"' '<TextBox x:Name="DocumentSearchBox" Width="205" Height="29" VerticalContentAlignment="Center" AutomationProperties.Name="Search active PDF" AutomationProperties.HelpText="Type text and press Enter. Shortcut Ctrl+F."' 'document search'
Replace-One 'ToolTip="Collapse navigation sidebar" />' 'ToolTip="Collapse navigation sidebar" AutomationProperties.Name="Collapse document navigation sidebar" />' 'navigation collapse'
Replace-One '<ListBox x:Name="PagesList" Grid.Row="1" SelectionMode="Extended" SelectionChanged="PagesList_SelectionChanged"' '<ListBox x:Name="PagesList" Grid.Row="1" SelectionMode="Extended" SelectionChanged="PagesList_SelectionChanged" AutomationProperties.Name="PDF page thumbnails" AutomationProperties.HelpText="Select, multi-select, reorder, rotate, duplicate, extract or delete PDF pages."' 'pages list'
Replace-One '<TreeView x:Name="OutlineTree" Background="Transparent" BorderThickness="0" Margin="6"' '<TreeView x:Name="OutlineTree" Background="Transparent" BorderThickness="0" Margin="6" AutomationProperties.Name="PDF bookmarks and outline"' 'outline tree'
Replace-One '<ListBox x:Name="SearchResultsList" Background="Transparent" BorderThickness="0" Margin="6"' '<ListBox x:Name="SearchResultsList" Background="Transparent" BorderThickness="0" Margin="6" AutomationProperties.Name="PDF search results"' 'search results'
Replace-One '<ListBox x:Name="AnnotationsList" Background="Transparent" BorderThickness="0" Margin="6"' '<ListBox x:Name="AnnotationsList" Background="Transparent" BorderThickness="0" Margin="6" AutomationProperties.Name="PDF comments and annotations"' 'annotations list'
Replace-One '<ListBox x:Name="AttachmentsList" Grid.Row="0" Background="Transparent" BorderThickness="0" Margin="6"' '<ListBox x:Name="AttachmentsList" Grid.Row="0" Background="Transparent" BorderThickness="0" Margin="6" AutomationProperties.Name="Embedded PDF attachments"' 'attachments list'
Replace-One '<ScrollViewer x:Name="PreviewScroll" Visibility="Collapsed" HorizontalScrollBarVisibility="Auto" VerticalScrollBarVisibility="Auto">' '<ScrollViewer x:Name="PreviewScroll" Visibility="Collapsed" HorizontalScrollBarVisibility="Auto" VerticalScrollBarVisibility="Auto" AutomationProperties.Name="Single-page PDF document view">' 'single page view'
Replace-One '<Image x:Name="PreviewImage" Stretch="None" RenderOptions.BitmapScalingMode="HighQuality" />' '<Image x:Name="PreviewImage" Stretch="None" RenderOptions.BitmapScalingMode="HighQuality" AutomationProperties.Name="Current rendered PDF page" />' 'preview image'
Replace-One '<Canvas x:Name="TextSelectionCanvas" Background="Transparent" Visibility="Collapsed" IsHitTestVisible="False" Focusable="True" Cursor="IBeam"' '<Canvas x:Name="TextSelectionCanvas" Background="Transparent" Visibility="Collapsed" IsHitTestVisible="False" Focusable="True" Cursor="IBeam" AutomationProperties.Name="Selectable PDF text layer" AutomationProperties.HelpText="Drag across text to select it, then press Ctrl+C or use annotation commands."' 'text selection layer'
Replace-One '<Canvas x:Name="MarkupCanvas" Background="Transparent" Visibility="Collapsed" Cursor="Cross"' '<Canvas x:Name="MarkupCanvas" Background="Transparent" Visibility="Collapsed" Cursor="Cross" AutomationProperties.Name="PDF annotation and editing canvas"' 'markup canvas'
Replace-One '<ListBox x:Name="ContinuousPagesList" Visibility="Collapsed" Background="Transparent" BorderThickness="0"' '<ListBox x:Name="ContinuousPagesList" Visibility="Collapsed" Background="Transparent" BorderThickness="0" AutomationProperties.Name="Continuous PDF reading view"' 'continuous view'

[IO.File]::WriteAllText($path,$text.Replace("`n","`r`n"),[Text.UTF8Encoding]::new($false))
Write-Host 'Screen-reader accessibility metadata staged by direct guarded replacements.' -ForegroundColor Green
